//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public string ImageAddress { get; set; }
        public string PostAddress { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
